# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'parameter_qt_copy.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QRadioButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(600, 300)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(600, 300))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 600, 210))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 10, 49, 21))
        font = QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 10, 49, 21))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(340, 10, 49, 21))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(490, 10, 49, 21))
        self.label_4.setFont(font)
        self.var_a = QCheckBox(self.frame)
        self.var_a.setObjectName(u"var_a")
        self.var_a.setGeometry(QRect(20, 50, 80, 21))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.var_a.sizePolicy().hasHeightForWidth())
        self.var_a.setSizePolicy(sizePolicy1)
        self.var_a.setFont(font)
#if QT_CONFIG(statustip)
        self.var_a.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_a.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_a.setIconSize(QSize(16, 16))
        self.var_b = QCheckBox(self.frame)
        self.var_b.setObjectName(u"var_b")
        self.var_b.setGeometry(QRect(20, 80, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_b.sizePolicy().hasHeightForWidth())
        self.var_b.setSizePolicy(sizePolicy1)
        self.var_b.setFont(font)
#if QT_CONFIG(statustip)
        self.var_b.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_b.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_b.setIconSize(QSize(16, 16))
        self.var_c = QCheckBox(self.frame)
        self.var_c.setObjectName(u"var_c")
        self.var_c.setGeometry(QRect(20, 110, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_c.sizePolicy().hasHeightForWidth())
        self.var_c.setSizePolicy(sizePolicy1)
        self.var_c.setFont(font)
#if QT_CONFIG(statustip)
        self.var_c.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_c.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_c.setIconSize(QSize(16, 16))
        self.var_d = QCheckBox(self.frame)
        self.var_d.setObjectName(u"var_d")
        self.var_d.setGeometry(QRect(20, 140, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_d.sizePolicy().hasHeightForWidth())
        self.var_d.setSizePolicy(sizePolicy1)
        self.var_d.setFont(font)
#if QT_CONFIG(statustip)
        self.var_d.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_d.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_d.setIconSize(QSize(16, 16))
        self.var_e = QCheckBox(self.frame)
        self.var_e.setObjectName(u"var_e")
        self.var_e.setGeometry(QRect(20, 170, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_e.sizePolicy().hasHeightForWidth())
        self.var_e.setSizePolicy(sizePolicy1)
        self.var_e.setFont(font)
#if QT_CONFIG(statustip)
        self.var_e.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_e.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_e.setIconSize(QSize(16, 16))
        self.var_f = QCheckBox(self.frame)
        self.var_f.setObjectName(u"var_f")
        self.var_f.setGeometry(QRect(170, 50, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_f.sizePolicy().hasHeightForWidth())
        self.var_f.setSizePolicy(sizePolicy1)
        self.var_f.setFont(font)
#if QT_CONFIG(statustip)
        self.var_f.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_f.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_f.setIconSize(QSize(16, 16))
        self.var_g = QCheckBox(self.frame)
        self.var_g.setObjectName(u"var_g")
        self.var_g.setGeometry(QRect(170, 80, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_g.sizePolicy().hasHeightForWidth())
        self.var_g.setSizePolicy(sizePolicy1)
        self.var_g.setFont(font)
#if QT_CONFIG(statustip)
        self.var_g.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_g.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_g.setIconSize(QSize(16, 16))
        self.var_h = QCheckBox(self.frame)
        self.var_h.setObjectName(u"var_h")
        self.var_h.setGeometry(QRect(170, 110, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_h.sizePolicy().hasHeightForWidth())
        self.var_h.setSizePolicy(sizePolicy1)
        self.var_h.setFont(font)
#if QT_CONFIG(statustip)
        self.var_h.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_h.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_h.setIconSize(QSize(16, 16))
        self.var_i = QCheckBox(self.frame)
        self.var_i.setObjectName(u"var_i")
        self.var_i.setGeometry(QRect(170, 140, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_i.sizePolicy().hasHeightForWidth())
        self.var_i.setSizePolicy(sizePolicy1)
        self.var_i.setFont(font)
#if QT_CONFIG(statustip)
        self.var_i.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_i.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_i.setIconSize(QSize(16, 16))
        self.var_j = QCheckBox(self.frame)
        self.var_j.setObjectName(u"var_j")
        self.var_j.setGeometry(QRect(170, 170, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_j.sizePolicy().hasHeightForWidth())
        self.var_j.setSizePolicy(sizePolicy1)
        self.var_j.setFont(font)
#if QT_CONFIG(statustip)
        self.var_j.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_j.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_j.setIconSize(QSize(16, 16))
        self.var_k = QCheckBox(self.frame)
        self.var_k.setObjectName(u"var_k")
        self.var_k.setGeometry(QRect(320, 50, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_k.sizePolicy().hasHeightForWidth())
        self.var_k.setSizePolicy(sizePolicy1)
        self.var_k.setFont(font)
#if QT_CONFIG(statustip)
        self.var_k.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_k.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_k.setIconSize(QSize(16, 16))
        self.var_l = QCheckBox(self.frame)
        self.var_l.setObjectName(u"var_l")
        self.var_l.setGeometry(QRect(320, 80, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_l.sizePolicy().hasHeightForWidth())
        self.var_l.setSizePolicy(sizePolicy1)
        self.var_l.setFont(font)
#if QT_CONFIG(statustip)
        self.var_l.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_l.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_l.setIconSize(QSize(16, 16))
        self.var_m = QCheckBox(self.frame)
        self.var_m.setObjectName(u"var_m")
        self.var_m.setGeometry(QRect(320, 110, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_m.sizePolicy().hasHeightForWidth())
        self.var_m.setSizePolicy(sizePolicy1)
        self.var_m.setFont(font)
#if QT_CONFIG(statustip)
        self.var_m.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_m.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_m.setIconSize(QSize(16, 16))
        self.var_n = QCheckBox(self.frame)
        self.var_n.setObjectName(u"var_n")
        self.var_n.setGeometry(QRect(320, 140, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_n.sizePolicy().hasHeightForWidth())
        self.var_n.setSizePolicy(sizePolicy1)
        self.var_n.setFont(font)
#if QT_CONFIG(statustip)
        self.var_n.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_n.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_n.setIconSize(QSize(16, 16))
        self.var_o = QCheckBox(self.frame)
        self.var_o.setObjectName(u"var_o")
        self.var_o.setGeometry(QRect(320, 170, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_o.sizePolicy().hasHeightForWidth())
        self.var_o.setSizePolicy(sizePolicy1)
        self.var_o.setFont(font)
#if QT_CONFIG(statustip)
        self.var_o.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_o.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_o.setIconSize(QSize(16, 16))
        self.var_p = QCheckBox(self.frame)
        self.var_p.setObjectName(u"var_p")
        self.var_p.setGeometry(QRect(470, 50, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_p.sizePolicy().hasHeightForWidth())
        self.var_p.setSizePolicy(sizePolicy1)
        self.var_p.setFont(font)
#if QT_CONFIG(statustip)
        self.var_p.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_p.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_p.setIconSize(QSize(16, 16))
        self.var_q = QCheckBox(self.frame)
        self.var_q.setObjectName(u"var_q")
        self.var_q.setGeometry(QRect(470, 80, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_q.sizePolicy().hasHeightForWidth())
        self.var_q.setSizePolicy(sizePolicy1)
        self.var_q.setFont(font)
#if QT_CONFIG(statustip)
        self.var_q.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_q.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_q.setIconSize(QSize(16, 16))
        self.var_r = QCheckBox(self.frame)
        self.var_r.setObjectName(u"var_r")
        self.var_r.setGeometry(QRect(470, 110, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_r.sizePolicy().hasHeightForWidth())
        self.var_r.setSizePolicy(sizePolicy1)
        self.var_r.setFont(font)
#if QT_CONFIG(statustip)
        self.var_r.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_r.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_r.setIconSize(QSize(16, 16))
        self.var_s = QCheckBox(self.frame)
        self.var_s.setObjectName(u"var_s")
        self.var_s.setGeometry(QRect(470, 140, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_s.sizePolicy().hasHeightForWidth())
        self.var_s.setSizePolicy(sizePolicy1)
        self.var_s.setFont(font)
#if QT_CONFIG(statustip)
        self.var_s.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_s.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_s.setIconSize(QSize(16, 16))
        self.var_t = QCheckBox(self.frame)
        self.var_t.setObjectName(u"var_t")
        self.var_t.setGeometry(QRect(470, 170, 80, 21))
        sizePolicy1.setHeightForWidth(self.var_t.sizePolicy().hasHeightForWidth())
        self.var_t.setSizePolicy(sizePolicy1)
        self.var_t.setFont(font)
#if QT_CONFIG(statustip)
        self.var_t.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.var_t.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.var_t.setIconSize(QSize(16, 16))
        self.lineEdit = QLineEdit(self.frame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(105, 10, 31, 21))
        font1 = QFont()
        font1.setPointSize(11)
        self.lineEdit.setFont(font1)
        self.lineEdit.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.lineEdit.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.lineEdit.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.line = QFrame(self.frame)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 30, 600, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.frame)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(140, 0, 20, 210))
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_3 = QFrame(self.frame)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(290, 0, 20, 210))
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.frame)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(440, 0, 20, 210))
        self.line_4.setFrameShape(QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.frame)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 200, 600, 16))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.lineEdit_2 = QLineEdit(self.frame)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(255, 10, 31, 21))
        self.lineEdit_2.setFont(font1)
        self.lineEdit_2.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_3 = QLineEdit(self.frame)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(405, 10, 31, 21))
        self.lineEdit_3.setFont(font1)
        self.lineEdit_3.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_4 = QLineEdit(self.frame)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(555, 10, 31, 21))
        self.lineEdit_4.setFont(font1)
        self.lineEdit_4.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_5 = QLineEdit(self.frame)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(105, 50, 31, 21))
        self.lineEdit_5.setFont(font1)
        self.lineEdit_5.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_6 = QLineEdit(self.frame)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(105, 80, 31, 21))
        self.lineEdit_6.setFont(font1)
        self.lineEdit_6.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_7 = QLineEdit(self.frame)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(105, 110, 31, 21))
        self.lineEdit_7.setFont(font1)
        self.lineEdit_7.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_7.setAutoFillBackground(False)
        self.lineEdit_7.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_7.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_8 = QLineEdit(self.frame)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(105, 140, 31, 21))
        self.lineEdit_8.setFont(font1)
        self.lineEdit_8.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_8.setAutoFillBackground(False)
        self.lineEdit_8.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_8.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_9 = QLineEdit(self.frame)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(105, 170, 31, 21))
        self.lineEdit_9.setFont(font1)
        self.lineEdit_9.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_9.setAutoFillBackground(False)
        self.lineEdit_9.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_9.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_10 = QLineEdit(self.frame)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(255, 140, 31, 21))
        self.lineEdit_10.setFont(font1)
        self.lineEdit_10.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_10.setAutoFillBackground(False)
        self.lineEdit_10.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_10.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_11 = QLineEdit(self.frame)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(255, 170, 31, 21))
        self.lineEdit_11.setFont(font1)
        self.lineEdit_11.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_11.setAutoFillBackground(False)
        self.lineEdit_11.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_11.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_12 = QLineEdit(self.frame)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(255, 110, 31, 21))
        self.lineEdit_12.setFont(font1)
        self.lineEdit_12.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_12.setAutoFillBackground(False)
        self.lineEdit_12.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_12.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_13 = QLineEdit(self.frame)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(255, 80, 31, 21))
        self.lineEdit_13.setFont(font1)
        self.lineEdit_13.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_13.setAutoFillBackground(False)
        self.lineEdit_13.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_13.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_14 = QLineEdit(self.frame)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(255, 50, 31, 21))
        self.lineEdit_14.setFont(font1)
        self.lineEdit_14.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_14.setAutoFillBackground(False)
        self.lineEdit_14.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_14.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_15 = QLineEdit(self.frame)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(405, 140, 31, 21))
        self.lineEdit_15.setFont(font1)
        self.lineEdit_15.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_15.setAutoFillBackground(False)
        self.lineEdit_15.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_15.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_16 = QLineEdit(self.frame)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(405, 170, 31, 21))
        self.lineEdit_16.setFont(font1)
        self.lineEdit_16.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_16.setAutoFillBackground(False)
        self.lineEdit_16.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_16.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_17 = QLineEdit(self.frame)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(405, 110, 31, 21))
        self.lineEdit_17.setFont(font1)
        self.lineEdit_17.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_17.setAutoFillBackground(False)
        self.lineEdit_17.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_17.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_18 = QLineEdit(self.frame)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(405, 80, 31, 21))
        self.lineEdit_18.setFont(font1)
        self.lineEdit_18.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_18.setAutoFillBackground(False)
        self.lineEdit_18.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_18.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_19 = QLineEdit(self.frame)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(405, 50, 31, 21))
        self.lineEdit_19.setFont(font1)
        self.lineEdit_19.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_19.setAutoFillBackground(False)
        self.lineEdit_19.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_19.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_20 = QLineEdit(self.frame)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(555, 140, 31, 21))
        self.lineEdit_20.setFont(font1)
        self.lineEdit_20.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_20.setAutoFillBackground(False)
        self.lineEdit_20.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_20.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_21 = QLineEdit(self.frame)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(555, 170, 31, 21))
        self.lineEdit_21.setFont(font1)
        self.lineEdit_21.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_21.setAutoFillBackground(False)
        self.lineEdit_21.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_21.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_22 = QLineEdit(self.frame)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(555, 110, 31, 21))
        self.lineEdit_22.setFont(font1)
        self.lineEdit_22.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_22.setAutoFillBackground(False)
        self.lineEdit_22.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_22.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_23 = QLineEdit(self.frame)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(555, 80, 31, 21))
        self.lineEdit_23.setFont(font1)
        self.lineEdit_23.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_23.setAutoFillBackground(False)
        self.lineEdit_23.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_23.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_24 = QLineEdit(self.frame)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(555, 50, 31, 21))
        self.lineEdit_24.setFont(font1)
        self.lineEdit_24.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.lineEdit_24.setAutoFillBackground(False)
        self.lineEdit_24.setInputMethodHints(Qt.InputMethodHint.ImhPreferNumbers)
        self.lineEdit_24.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 210, 600, 50))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.radioButton = QRadioButton(self.frame_2)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(20, 10, 61, 21))
        self.radioButton.setFont(font1)
        self.radioButton_2 = QRadioButton(self.frame_2)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(80, 10, 71, 21))
        self.radioButton_2.setFont(font1)
        self.label_25 = QLabel(self.frame_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, 10, 71, 21))
        self.label_25.setFont(font)
        self.label_25.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit_25 = QLineEdit(self.frame_2)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setGeometry(QRect(230, 10, 221, 21))
        self.lineEdit_25.setFont(font)
        self.pushButton = QPushButton(self.frame_2)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(460, 10, 71, 21))
        font2 = QFont()
        font2.setPointSize(10)
        self.pushButton.setFont(font2)
        self.pushButton_2 = QPushButton(self.frame_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(540, 10, 51, 21))
        self.pushButton_2.setFont(font2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 600, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u3010\u8eab\u4f53\u3011", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u3010\u6280\u91cf\u3011", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u3010\u5fc3\u9b42\u3011", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u3010\u793e\u4f1a\u3011", None))
        self.var_a.setText(QCoreApplication.translate("MainWindow", u"\u2605\u767d\u5175\uff1a", None))
        self.var_b.setText(QCoreApplication.translate("MainWindow", u"\u3000\u904b\u52d5\uff1a", None))
        self.var_c.setText(QCoreApplication.translate("MainWindow", u"\u3000\u9811\u5065\uff1a", None))
        self.var_d.setText(QCoreApplication.translate("MainWindow", u"\u3000\u64cd\u7e26\uff1a", None))
        self.var_e.setText(QCoreApplication.translate("MainWindow", u"\u3000\u77e5\u899a\uff1a", None))
        self.var_f.setText(QCoreApplication.translate("MainWindow", u"\u2605\u5c04\u6483\uff1a", None))
        self.var_g.setText(QCoreApplication.translate("MainWindow", u"\u3000\u533b\u7642\uff1a", None))
        self.var_h.setText(QCoreApplication.translate("MainWindow", u"\u3000\u96a0\u5bc6\uff1a", None))
        self.var_i.setText(QCoreApplication.translate("MainWindow", u"\u3000\u5de5\u4f5c\uff1a", None))
        self.var_j.setText(QCoreApplication.translate("MainWindow", u"\u3000\u635c\u67fb\uff1a", None))
        self.var_k.setText(QCoreApplication.translate("MainWindow", u"\u2605\u546a\u6cd5\uff1a", None))
        self.var_l.setText(QCoreApplication.translate("MainWindow", u"\u3000\u610f\u5fd7\uff1a", None))
        self.var_m.setText(QCoreApplication.translate("MainWindow", u"\u3000\u770b\u7834\uff1a", None))
        self.var_n.setText(QCoreApplication.translate("MainWindow", u"\u3000\u82b8\u80fd\uff1a", None))
        self.var_o.setText(QCoreApplication.translate("MainWindow", u"\u3000\u4f1d\u627f\uff1a", None))
        self.var_p.setText(QCoreApplication.translate("MainWindow", u"\u2605\u7b56\u8b00\uff1a", None))
        self.var_q.setText(QCoreApplication.translate("MainWindow", u"\u3000\u6559\u990a\uff1a", None))
        self.var_r.setText(QCoreApplication.translate("MainWindow", u"\u3000\u4ea4\u6e09\uff1a", None))
        self.var_s.setText(QCoreApplication.translate("MainWindow", u"\u3000\u96fb\u8133\uff1a", None))
        self.var_t.setText(QCoreApplication.translate("MainWindow", u"\u3000\u5bb9\u59ff\uff1a", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_3.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_4.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_5.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_6.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_7.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_8.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_9.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_10.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_11.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_12.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_13.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_14.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_15.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_16.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_17.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_18.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_19.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_20.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_21.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_22.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_23.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.lineEdit_24.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"\u5deb\u89a1", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"\u4ed8\u55aa\u795e", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"\u30ad\u30e3\u30e9\u540d\uff1a", None))
        self.lineEdit_25.setText(QCoreApplication.translate("MainWindow", u"\u3042\u3042\u3042\u3042\u3042", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u753b\u50cf\u4f5c\u6210", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u30ea\u30bb\u30c3\u30c8", None))
    # retranslateUi

